# Generated by Django 4.2.1 on 2023-07-06 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('blood_bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_bank_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'blood_bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('blood_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_group_type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'blood_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonarDetails',
            fields=[
                ('donar_id', models.AutoField(primary_key=True, serialize=False)),
                ('donar_name', models.CharField(max_length=45)),
                ('units', models.IntegerField()),
                ('contact_number', models.BigIntegerField()),
                ('aadhar_number', models.CharField(max_length=45, unique=True)),
                ('transfusion_date', models.DateField(default=datetime.date.today)),
                ('eligibility', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'donar_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=45)),
                ('area', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('contact_number', models.BigIntegerField()),
                ('hospital_name', models.CharField(max_length=45)),
                ('status', models.CharField(default='requested', max_length=45)),
                ('units_required', models.IntegerField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'patient_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalUnits',
            fields=[
                ('total_units_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_units', models.IntegerField()),
            ],
            options={
                'db_table': 'total_units',
                'managed': False,
            },
        ),
    ]
