# Generated by Django 4.2.1 on 2023-07-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'managed': False},
        ),
    ]
